const HTTP_STATUS_CODES = {
  CODES: {
  SUCCESS: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  INTERNAL_SERVER_ERROR: 500,
  DATA_NOT_FOUND: 404,
  FORBIDDEN: 403
  },
};

module.exports = HTTP_STATUS_CODES;
